---
name: Snapcast Server (Andreas fork)
version: 0.1.94
slug: snapcastserver_andreas
description: "Snapcast server with bluetooth input"
url: https://github.com/AndreasNorefalk/addon-snapserver
codenotary: andreasnorefalk@users.noreply.github.com
arch:
  - aarch64
  - amd64
  - armv7
  - i386
host_network: true
devices:
  - /dev/bus/usb:/dev/bus/usb
privileged:
  - NET_ADMIN
  - SYS_ADMIN
startup: services   # Starts early, before apps
boot: auto          # Starts automatically at boot
map: ["share:rw"]
audio: true
init: false
options:
  streams: |
    spotify:///librespot?name=Spotify&bitrate=320
    pipe:///tmp/snapfifo?name=Bluetooth&sampleformat=44100:16:2&type=pipe&mode=read
  buffer: 1000
  codec: "flac"
  send_to_muted: "false"
  sampleformat: "44100:16:2"
  http_enabled: "true"
  tcp_enabled: "true"
  logging_enabled: "true"
  server_threads: -1
  server_datadir: "/usr/share/snapserver/snapweb"
  initial_volume: 100
schema:
  streams: str
  buffer: int
  codec: str
  send_to_muted: str
  sampleformat: str
  http_enabled: str
  tcp_enabled: str
  logging_enabled: str
  server_threads: int
  server_datadir: str
  initial_volume: int
  stream_bis: str?
  stream_ter: str?
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  4953/tcp: 4953
