#!/command/with-contenv bash
# shellcheck shell=bash

# Load Bashio logging helpers.
# shellcheck disable=SC1091
source /usr/lib/bashio.sh

bashio::log.info "[dmesg] Reducing kernel console verbosity"
if ! dmesg -n 1 &>/dev/null; then
    bashio::log.warning "[dmesg] Unable to adjust kernel console verbosity"
fi
